# Generated by Django 6.0.1 on 2026-03-28 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='photo',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
